apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: g9a5tgpeb-nodejs 
  janus-idp.io/tekton: g9a5tgpeb-nodejs
  backstage.io/kubernetes-id: g9a5tgpeb-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g9a5tgpeb-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml