apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: g9a5tgpeb-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: g9a5tgpeb-nodejs 
  name: g9a5tgpeb-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: g9a5tgpeb-nodejs 
